#!/bin/bash +x

params=$@

if [ $params =~ -- ]
then
    echo "Two parts"
else
    echo "one part"
fi

exit 0

if [ $# -eq 0 ]
	then
	echo "You need to pass something."
	exit 1
fi

COMMAND=$1

tempfile=$(mktemp job.XXX)
echo "Working with $tempfile"

# submit jobs to the grid engine
# qsub -S /bin/bash -sync y $tempfile
qsub -S /bin/bash -sync y <<-EOF
	#SGE submission options
	#$ -cwd
	#$ -V
	#$ -t 1-9
	#$ -N $tempfile
	export OMP_NUM_THREADS=1
	num=$(printf "%d00" $SGE_TASK_ID)

	cd $num 
	make $COMMAND

	echo "command: $COMMAND"
EOF

rm $tempfile